### ISSUE TITLE
Cannot find module 'bundle-loader?lazy!../pages/register/Register' from 'App.js'

### ISSUE THREAD

**Issue by alexb-uk** [flatlogic/react-dashboard#3]
I've just cloned the repo and successfully performed `yarn install` + `yarn start` and have the example dashboard up and running which is great.

However when I run the tests I get the following error:

```bash
$ yarn test
yarn run v1.1.0
$ jest

 FAIL  src\components\Layout\Layout.test.js
  ● Test suite failed to run

    Cannot find module 'bundle-loader?lazy!../pages/register/Register' from 'App.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/components/App.js:20:374)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.06s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not familiar with bundle-loader so thought I would ask on here in case it was an easy fix.

Many Thanks for making the skeleton public as RSK + React Router v4 is exactly what I'm looking for and being a complete Node.js novice hopefully this will give me a really big boost.

Cheers

Alex

_System Info:_
```
Windows 10 Pro
node v6.10.3
npm 3.10.10
yarn 1.1.0
```

**Comment by jgardezi** [comment]
+1 - I am getting the similar issue.

**System Info:**
`
macOS High Sierra
node v8.9.1
npm 5.5.1
yarn 1.3.2
`

**Comment by koerbcm** [comment]
I am getting the same issue too. I can't seem to use Bundle or withMeta correctly. I know nothing about bundle-loader and Google is turning up nothing. Could anyone help with this?

**Comment by strefethen** [comment]
+1
@okendoken any input on this?

Thanks
